language: cpp
compiler:
  - gcc
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq qtdeclarative5-dev
before_script:
 - /usr/lib/x86_64-linux-gnu/qt5/bin/qmake Trackbox.pro -r -spec linux-g++
script: make


